# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\script.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Script(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(512, 512)
        self.scriptHandlerHeader = QtWidgets.QLabel(Form)
        self.scriptHandlerHeader.setGeometry(QtCore.QRect(10, 10, 491, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scriptHandlerHeader.setFont(font)
        self.scriptHandlerHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.scriptHandlerHeader.setObjectName("scriptHandlerHeader")
        self.scriptOutput = QtWidgets.QTextEdit(Form)
        self.scriptOutput.setGeometry(QtCore.QRect(10, 410, 491, 91))
        font = QtGui.QFont()
        font.setFamily("Cascadia Mono")
        font.setPointSize(10)
        self.scriptOutput.setFont(font)
        self.scriptOutput.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-style: solid;\n"
"border-width: 2px")
        self.scriptOutput.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.scriptOutput.setObjectName("scriptOutput")
        self.scriptEditor = QtWidgets.QTextEdit(Form)
        self.scriptEditor.setGeometry(QtCore.QRect(10, 60, 491, 271))
        self.scriptEditor.setMaximumSize(QtCore.QSize(512, 512))
        font = QtGui.QFont()
        font.setFamily("Cascadia Code")
        font.setPointSize(12)
        self.scriptEditor.setFont(font)
        self.scriptEditor.setAutoFormatting(QtWidgets.QTextEdit.AutoAll)
        self.scriptEditor.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.scriptEditor.setObjectName("scriptEditor")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 365, 491, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 340, 491, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.runButtonScript = QtWidgets.QPushButton(self.frame)
        self.runButtonScript.setGeometry(QtCore.QRect(0, 0, 75, 31))
        self.runButtonScript.setObjectName("runButtonScript")
        self.clearButtonScript = QtWidgets.QPushButton(self.frame)
        self.clearButtonScript.setGeometry(QtCore.QRect(420, 0, 71, 31))
        self.clearButtonScript.setObjectName("clearButtonScript")
        self.scriptHandlerUnder = QtWidgets.QLabel(Form)
        self.scriptHandlerUnder.setGeometry(QtCore.QRect(180, 40, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.scriptHandlerUnder.setFont(font)
        self.scriptHandlerUnder.setObjectName("scriptHandlerUnder")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.scriptHandlerHeader.setText(_translate("Form", "fNotes .py Handler"))
        self.scriptOutput.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Cascadia Mono\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.scriptOutput.setPlaceholderText(_translate("Form", "Script Output"))
        self.runButtonScript.setText(_translate("Form", "Run"))
        self.clearButtonScript.setText(_translate("Form", "Clear"))
        self.scriptHandlerUnder.setText(_translate("Form", "This might be slightly unstable ^^"))
