# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\table.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UI_Dialog_Table(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 440, 621, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.headerLabelTable = QtWidgets.QLabel(Dialog)
        self.headerLabelTable.setGeometry(QtCore.QRect(10, 20, 621, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.headerLabelTable.setFont(font)
        self.headerLabelTable.setAlignment(QtCore.Qt.AlignCenter)
        self.headerLabelTable.setObjectName("headerLabelTable")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 70, 581, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(128)
        self.gridLayout.setObjectName("gridLayout")
        self.rowsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rowsLabel.setFont(font)
        self.rowsLabel.setObjectName("rowsLabel")
        self.gridLayout.addWidget(self.rowsLabel, 0, 1, 1, 1)
        self.Columns = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.Columns.setProperty("value", 1)
        self.Columns.setObjectName("Columns")
        self.gridLayout.addWidget(self.Columns, 1, 0, 1, 1)
        self.Rows = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.Rows.setProperty("value", 1)
        self.Rows.setObjectName("Rows")
        self.gridLayout.addWidget(self.Rows, 0, 0, 1, 1)
        self.columnsLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.columnsLabel.setFont(font)
        self.columnsLabel.setObjectName("columnsLabel")
        self.gridLayout.addWidget(self.columnsLabel, 1, 1, 1, 1)
        self.borderStyle = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.borderStyle.setObjectName("borderStyle")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.borderStyle.addItem("")
        self.gridLayout.addWidget(self.borderStyle, 2, 0, 1, 1)
        self.borderStyleLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.borderStyleLabel.setFont(font)
        self.borderStyleLabel.setObjectName("borderStyleLabel")
        self.gridLayout.addWidget(self.borderStyleLabel, 2, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.headerLabelTable.setText(_translate("Dialog", "Table Designer"))
        self.rowsLabel.setText(_translate("Dialog", "Rows"))
        self.columnsLabel.setText(_translate("Dialog", "Columns"))
        self.borderStyle.setItemText(0, _translate("Dialog", "Solid"))
        self.borderStyle.setItemText(1, _translate("Dialog", "Dashed"))
        self.borderStyle.setItemText(2, _translate("Dialog", "DotDash"))
        self.borderStyle.setItemText(3, _translate("Dialog", "DotDotDash"))
        self.borderStyle.setItemText(4, _translate("Dialog", "Dotted"))
        self.borderStyle.setItemText(5, _translate("Dialog", "Double"))
        self.borderStyle.setItemText(6, _translate("Dialog", "Groove"))
        self.borderStyle.setItemText(7, _translate("Dialog", "Inset"))
        self.borderStyle.setItemText(8, _translate("Dialog", "None"))
        self.borderStyle.setItemText(9, _translate("Dialog", "Outset"))
        self.borderStyle.setItemText(10, _translate("Dialog", "Ridge"))
        self.borderStyleLabel.setText(_translate("Dialog", "Border Style"))
